name: crawl news and save data

on:
  schedule:
    - cron: '30 5 * * *'
  pull_request:
  push:

jobs:
  crawl-economists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: git clone https://${{secrets.ACCESS_TOKEN}}@github.com/ahacad/newscloud-data
      - run: mkdir -p newscloud-data
      - run: python src/backend/src/crawl.py --folder newscloud-data
      - run: |
            git config --global user.email "ahacad@bot.com"
            git config --global user.name "ahacadbot"
            cd newscloud-data
            git add .
            git commit -m "update crawled data $(date)"
            git push
